version: '4.30'
services:
  mysql:
    image: mysql:latest
    ports:
      - "3380:3380"
    environment:
      MYSQL_ROOT_PASSWORD: rootpass1234
      MYSQL_DATABASE: PencaUCU
    volumes:
      - ./init_database.sql:/docker-entrypoint-initdb.d/init_database.sql
  
  backend:
    build:
      context: ./Back
      dockerfile: Dockerfile-backend
    ports:
      - "3000:3000"
    env_file:
      - ./Back/.env
    depends_on:
      - mysql
    command: npm run dev


  frontend:
    build:
      context: ./Front2
      dockerfile: Dockerfile-frontend
    ports:
      - "4200:4200"
    depends_on:
      - backend
    command: ng serve --host 0.0.0.0 --port 4200
