# Usa una imagen base de Node.js
FROM node:14

# Establece el directorio de trabajo
WORKDIR /app

# Copia el package.json y el package-lock.json
COPY package*.json ./

# Instala las dependencias
RUN npm install

# Copia el resto de la aplicación
COPY . .

# Copia el archivo .env
COPY .env .env

# Expone el puerto que la aplicación usará
EXPOSE 3006

# Comando para ejecutar la aplicación
CMD ["npm", "run", "dev"]
