# Usar la imagen de Node como base para compilar la aplicación Angular
FROM node:18.20.3-alpine3.18 AS build

# Directorio de trabajo en el contenedor
WORKDIR /app

# Copiar el código fuente del frontend al contenedor
COPY  . /app

# Instalar Angular CLI (si no está instalado)
RUN npm install -g @angular/cli

# Instalar las dependencias del frontend
RUN npm install

# Construir la aplicación de Angular
RUN ng build

# Segunda etapa para la imagen final
FROM nginx:alpine

# Copiar los archivos compilados de Angular al directorio de NGINX
COPY --from=build /app/dist/front2 /usr/share/nginx/html

# Puerto en el que escucha nginx
EXPOSE 80

# Comando para iniciar el servidor nginx
CMD ["nginx", "-g", "daemon off;"]
