# Usar la imagen de Node como base para compilar la aplicación Angular
FROM node:14 AS build

# Directorio de trabajo en el contenedor
WORKDIR /app

# Copiar el código fuente del frontend al contenedor
COPY Front2 /app

# Instalar Angular CLI (si no está instalado)
RUN npm install -g @angular/cli

# Instalar las dependencias del frontend
RUN npm install

# Construir la aplicación de Angular
RUN ng build

# Segunda etapa para la imagen final
FROM docker.io/library/nginx:alpine

# Copiar los archivos compilados de Angular al directorio de NGINX
COPY --from=build-stage /app/dist/front-bdd /usr/share/nginx/html

# Puerto en el que escucha nginx
EXPOSE 4200

# Comando para iniciar el servidor nginx
CMD ["nginx", "-g", "daemon off;"]
